# Generated by Django 3.2.2 on 2021-05-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microposts', '0003_alter_post_id'),
        ('accounts', '0004_auto_20210515_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='favoritePost',
            field=models.ManyToManyField(blank=True, to='microposts.Post', verbose_name='お気に入りの投稿'),
        ),
    ]
